// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edu2WebAPI.Data;

namespace edu2WebAPI.Migrations
{
    [DbContext(typeof(Edu2DbContext))]
    [Migration("20210309181313_SeedData5")]
    partial class SeedData5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProjectTag");
                });

            modelBuilder.Entity("TagUserSettings", b =>
                {
                    b.Property<int>("UserSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("UserTagsId")
                        .HasColumnType("int");

                    b.HasKey("UserSettingsId", "UserTagsId");

                    b.HasIndex("UserTagsId");

                    b.ToTable("TagUserSettings");
                });

            modelBuilder.Entity("edu2Domain.CollaboratorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CollaboratorProfile");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CollaboratorProfile");
                });

            modelBuilder.Entity("edu2Domain.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Patre 5, 78000 Banja Luka",
                            Name = "Elektrotehnički fakultet"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Vojvode Stepe Stepanovića 71, 78000 Banja Luka",
                            Name = "Mašinski fakultet"
                        });
                });

            modelBuilder.Entity("edu2Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudyFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Opis projekta",
                            ProjectStatus = 1,
                            StudyFieldId = 1,
                            Title = "Naslov projekta"
                        });
                });

            modelBuilder.Entity("edu2Domain.ProjectApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicantComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CollaboratorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectApplicationStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("CollaboratorProfileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantId = 2,
                            CollaboratorProfileId = 1,
                            ProjectApplicationStatus = 3,
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("edu2Domain.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Social");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Website"
                        },
                        new
                        {
                            Id = 2,
                            Name = "LinkedIn"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ResearchGate"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Twitter"
                        });
                });

            modelBuilder.Entity("edu2Domain.StudyField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("Key", 0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Računarske nauke"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Opšta elektrotehnika"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Automatika i robotika"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telekomunikacije"
                        });
                });

            modelBuilder.Entity("edu2Domain.StudyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("DurationYears")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("StudyProgram");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cycle = 1,
                            DurationYears = 4,
                            FacultyId = 1,
                            Name = "Računarstvo i informatika"
                        },
                        new
                        {
                            Id = 2,
                            Cycle = 1,
                            DurationYears = 4,
                            FacultyId = 1,
                            Name = "Elektronika i telekomunikacije"
                        },
                        new
                        {
                            Id = 3,
                            Cycle = 1,
                            DurationYears = 4,
                            FacultyId = 1,
                            Name = "Elektroenergetika i automatika"
                        },
                        new
                        {
                            Id = 4,
                            Cycle = 2,
                            DurationYears = 1,
                            FacultyId = 1,
                            Name = "Računarstvo i informatika"
                        },
                        new
                        {
                            Id = 5,
                            Cycle = 2,
                            DurationYears = 1,
                            FacultyId = 1,
                            Name = "Elektronika i telekomunikacije"
                        },
                        new
                        {
                            Id = 6,
                            Cycle = 2,
                            DurationYears = 1,
                            FacultyId = 1,
                            Name = "Elektroenergetski i industrijski sistemi"
                        },
                        new
                        {
                            Id = 7,
                            Cycle = 2,
                            DurationYears = 1,
                            FacultyId = 1,
                            Name = "Digitalno emitovanje i širokopojasne tehnologije"
                        },
                        new
                        {
                            Id = 8,
                            Cycle = 3,
                            DurationYears = 3,
                            FacultyId = 1,
                            Name = "Informaciono-komunikacione tehnologije"
                        },
                        new
                        {
                            Id = 9,
                            Cycle = 1,
                            DurationYears = 4,
                            FacultyId = 2,
                            Name = "Mehatronika"
                        },
                        new
                        {
                            Id = 10,
                            Cycle = 1,
                            DurationYears = 4,
                            FacultyId = 2,
                            Name = "Industrijsko inženjerstvo"
                        });
                });

            modelBuilder.Entity("edu2Domain.StudyProgramSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudyProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("StudyProgramSpecialization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Računarski inženjering",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Softverski inženjering",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Elektronika",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telekomunikacije",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Elektroenergetika",
                            StudyProgramId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Automatika",
                            StudyProgramId = 3
                        });
                });

            modelBuilder.Entity("edu2Domain.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("Key", 0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "web"
                        },
                        new
                        {
                            Id = 2,
                            Name = "desktop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "mobile"
                        },
                        new
                        {
                            Id = 4,
                            Name = "iot"
                        });
                });

            modelBuilder.Entity("edu2Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserSettingsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingsId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("edu2Domain.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("PhoneVisible")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProjectsVisible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Sample bio",
                            EmailVisible = true,
                            PhoneVisible = true,
                            ProjectsVisible = true
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Another sample bio",
                            EmailVisible = true,
                            PhoneVisible = true,
                            ProjectsVisible = true
                        });
                });

            modelBuilder.Entity("edu2Domain.UserSocials", b =>
                {
                    b.Property<int>("SocialId")
                        .HasColumnType("int");

                    b.Property<int>("UserSettingsId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialId", "UserSettingsId");

                    b.HasIndex("UserSettingsId");

                    b.ToTable("UserSocials");

                    b.HasData(
                        new
                        {
                            SocialId = 1,
                            UserSettingsId = 1,
                            Value = "ngrahovac.com"
                        },
                        new
                        {
                            SocialId = 2,
                            UserSettingsId = 1,
                            Value = "www.linkedin.com/nikolina-grahovac"
                        });
                });

            modelBuilder.Entity("edu2WebAPI.Auth.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("UserAccountType")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "255fd95b-c771-4be6-852c-5634244b17ac",
                            Email = "nikolinagrahovac@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "NIKOLINAGRAHOVAC@TEST.COM",
                            NormalizedUserName = "NIKOLINAGRAHOVAC@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB3fErhGcr/yNJzrnpwkMN0eSAjxvNKxRhnu+pc/nKkNmCuBIFm9Hb6ow4nuD2EBrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "BRPZ5G5VMPU533RX5YC3S62EYN5H22EL",
                            TwoFactorEnabled = false,
                            UserAccountType = 0,
                            UserName = "nikolinagrahovac@test.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80088041-9c29-474a-8668-3277462c4d51",
                            Email = "zoranpantos@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ZORANPANTOS@TEST.COM",
                            NormalizedUserName = "ZORANPANTOS@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFhPDeoQp9iRyCWYDdk+1+BVvrNObJl/WW/vJBiezvzhe69X92GG4+z9XUzHS8qN3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7ZTQGH5Q7AX4CPI73DWSQS2OMESYR6KT",
                            TwoFactorEnabled = false,
                            UserAccountType = 0,
                            UserName = "zoranpantos@test.com"
                        });
                });

            modelBuilder.Entity("edu2Domain.FacultyMemberProfile", b =>
                {
                    b.HasBaseType("edu2Domain.CollaboratorProfile");

                    b.Property<int?>("StudyFieldId")
                        .HasColumnType("int");

                    b.HasIndex("StudyFieldId");

                    b.HasDiscriminator().HasValue("FacultyMemberProfile");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "Profil nastavnog saradnika",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("edu2Domain.StudentProfile", b =>
                {
                    b.HasBaseType("edu2Domain.CollaboratorProfile");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyCycle")
                        .HasColumnType("int");

                    b.Property<int?>("StudyProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyProgramSpecializationId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyYear")
                        .HasColumnType("int");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("StudyProgramSpecializationId");

                    b.HasDiscriminator().HasValue("StudentProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Studentski profil",
                            ProjectId = 1,
                            FacultyId = 1
                        });
                });

            modelBuilder.Entity("edu2Domain.FacultyMember", b =>
                {
                    b.HasBaseType("edu2Domain.User");

                    b.Property<int>("AcademicRank")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyMember_FacultyId");

                    b.Property<int?>("StudyFieldId")
                        .HasColumnType("int");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudyFieldId");

                    b.HasDiscriminator().HasValue("FacultyMember");
                });

            modelBuilder.Entity("edu2Domain.Student", b =>
                {
                    b.HasBaseType("edu2Domain.User");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyProgramSpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("StudyYear")
                        .HasColumnType("int");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("StudyProgramSpecializationId");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserSettingsId = 1,
                            FacultyId = 1,
                            StudyProgramId = 1,
                            StudyProgramSpecializationId = 2,
                            StudyYear = 4
                        },
                        new
                        {
                            Id = 2,
                            UserSettingsId = 2,
                            FacultyId = 1,
                            StudyProgramId = 1,
                            StudyProgramSpecializationId = 2,
                            StudyYear = 3
                        });
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.HasOne("edu2Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu2Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagUserSettings", b =>
                {
                    b.HasOne("edu2Domain.UserSettings", null)
                        .WithMany()
                        .HasForeignKey("UserSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu2Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("UserTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("edu2Domain.CollaboratorProfile", b =>
                {
                    b.HasOne("edu2Domain.Project", "Project")
                        .WithMany("CollaboratorProfiles")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("edu2Domain.Project", b =>
                {
                    b.HasOne("edu2Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu2Domain.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("edu2Domain.ProjectApplication", b =>
                {
                    b.HasOne("edu2Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu2Domain.CollaboratorProfile", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu2Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("edu2Domain.StudyProgram", b =>
                {
                    b.HasOne("edu2Domain.Faculty", null)
                        .WithMany("StudyPrograms")
                        .HasForeignKey("FacultyId");
                });

            modelBuilder.Entity("edu2Domain.StudyProgramSpecialization", b =>
                {
                    b.HasOne("edu2Domain.StudyProgram", null)
                        .WithMany("ProgramSpecializations")
                        .HasForeignKey("StudyProgramId");
                });

            modelBuilder.Entity("edu2Domain.User", b =>
                {
                    b.HasOne("edu2Domain.UserSettings", "UserSettings")
                        .WithMany()
                        .HasForeignKey("UserSettingsId");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("edu2Domain.UserSocials", b =>
                {
                    b.HasOne("edu2Domain.Social", "Social")
                        .WithMany("UserSocials")
                        .HasForeignKey("SocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu2Domain.UserSettings", "UserSettings")
                        .WithMany("UserSocials")
                        .HasForeignKey("UserSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Social");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("edu2Domain.FacultyMemberProfile", b =>
                {
                    b.HasOne("edu2Domain.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("edu2Domain.StudentProfile", b =>
                {
                    b.HasOne("edu2Domain.Faculty", null)
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("edu2Domain.StudyProgram", null)
                        .WithMany()
                        .HasForeignKey("StudyProgramId");

                    b.HasOne("edu2Domain.StudyProgramSpecialization", null)
                        .WithMany()
                        .HasForeignKey("StudyProgramSpecializationId");
                });

            modelBuilder.Entity("edu2Domain.FacultyMember", b =>
                {
                    b.HasOne("edu2Domain.Faculty", null)
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu2Domain.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("edu2Domain.Student", b =>
                {
                    b.HasOne("edu2Domain.Faculty", null)
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu2Domain.StudyProgram", null)
                        .WithMany()
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu2Domain.StudyProgramSpecialization", null)
                        .WithMany()
                        .HasForeignKey("StudyProgramSpecializationId");
                });

            modelBuilder.Entity("edu2Domain.Faculty", b =>
                {
                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("edu2Domain.Project", b =>
                {
                    b.Navigation("CollaboratorProfiles");
                });

            modelBuilder.Entity("edu2Domain.Social", b =>
                {
                    b.Navigation("UserSocials");
                });

            modelBuilder.Entity("edu2Domain.StudyProgram", b =>
                {
                    b.Navigation("ProgramSpecializations");
                });

            modelBuilder.Entity("edu2Domain.UserSettings", b =>
                {
                    b.Navigation("UserSocials");
                });
#pragma warning restore 612, 618
        }
    }
}
